src/ethvalu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import UserRegisterView
from hashtags.api.views import TagTweetAPIView
from hashtags.views import HashTagView
from tweets.views import TweetListView
from tweets.api.views import SearchTweetAPIView
from .views import home, SearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^$', TweetListView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^profiles/', include('accounts.urls', namespace='profiles')),
    url(r'^tokens/', include('tokens.urls', namespace='tokens')),
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagTweetAPIView.as_view(), name='tag-tweet-api'),
    url(r'^api/search/$', SearchTweetAPIView.as_view(), name='search-api'),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    url(r'^api/', include('accounts.api.urls', namespace='profiles-api')),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^transaction/', include('transactions.urls', namespace='transaction')),
]

if settings.DEBUG:
    urlpatterns+= (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns+= (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/tokens/urls.py
from django.conf.urls import url
from .views import (
	BuyUserTokenView,
    SellUserTokenView,
	BuyTokenView,
    SellTokenView,
	BuyTokenConfirmView,
    SellTokenConfirmView,
	MyAssetTokensView,
    TokenIssueView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/buy_token$', BuyUserTokenView.as_view(), name='buy_token'),
    url(r'^(?P<username>[\w.@+-]+)/sell_token$', SellUserTokenView.as_view(), name='sell_token'),
    url(r'^(?P<username>[\w.@+-]+)/buy/$', BuyTokenView.as_view(), name='buy'),
    url(r'^(?P<username>[\w.@+-]+)/sell/$', SellTokenView.as_view(), name='sell'),
    url(r'^(?P<username>[\w.@+-]+)/buy/confirm$', BuyTokenConfirmView.as_view(), name='buy_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/sell/confirm$', SellTokenConfirmView.as_view(), name='sell_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/asset$', MyAssetTokensView.as_view(), name='asset'),
    url(r'^issue/$', TokenIssueView.as_view(), name='issue'),
    # url(r'^buy/$', BuyTokenView.as_view(), name='buy')
]

src/templates/delete-modal.html
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
     {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn deleteBtn btn-primary" value='Delete' href='/tweet'>Delete</button>
        <!-- <input type="submit" class="btn deleteBtn btn-primary" value='Delete' href='/tweet/' + {{ tweetValue.id }}/''> -->
      </div>
    </div>
  </div>
</div>

src/templates/error.html
{% extends "base.html" %}

{% block title %} {{ block.super }}| Welcome{% endblock title %}

{% block content %}
<h1>error</h1>
{% endblock content%}

src/templates/home.html
{% extends "base.html" %}

{% block title %} {{ block.super }}| Welcome{% endblock title %}

{% block content %}
<h1>Hi</h1>
{% endblock content%}

src/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">BLOWme</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    {% if request.user.is_authenticated %}
    {% include "tweets/search_form.html" %}
    {% endif %}
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      {% if request.user.is_authenticated %}
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          {% if request.user.profile.image %}
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <img class="profile-image img-circle nav-profile" src="{{ request.user.profile.image.url }}" >
           Account <span class="caret"></span></a>
          {% else %}
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Account <span class="caret"></span></a>
          {% endif %}
          <ul class="dropdown-menu">
            <li><a href="{{ request.user.profile.get_absolute_url }}">Profile</a></li>
            <li><a href="{{ request.user.profile.get_absolute_url }}update_profile">Edit Profile</a></li>
            <li><a href="{% url 'tokens:asset' username=request.user.username %}">My Tokens</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
      </ul>
      {% else %}
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
      </ul>
      {% endif %}


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

src/templates/reply-modal.html
<!-- Modal -->
<div class="modal fade" id="replyModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    <form class='form tweet-form'> {% csrf_token %}
      <div class="modal-header">
        <h5 class="modal-title" id="replyModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

          <textarea id='tweetReplyArea' class='form-control' name='content'></textarea>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <input type="submit" class="btn btn-primary" value='Reply'>
      </div>
      </form>
    </div>
  </div>
</div>

src/templates/search.html
{% extends "base.html" %}

{% block script %}
<script>
    $(document).ready(function(){
        loadTweetContainer("tweet-container")
    });
</script>
{% endblock script %}

{% block content %}
    <div class='row'>
        <div class='col-sm-12'>
            {% if request.GET.q %}
            <p class='lead'>Results for {{ request.GET.q }}</p>
            {% endif %}
        </div>
        <div class='col-sm-9'>
            <h1>Tweets</h1>
            <hr/>
            <div id='tweet-container' data-url='/api/search/'></div>
            <a href='#' id='loadmore'>Load More</a>
        </div>
        <div class='col-sm-3'>
            <h1>Users</h1>
            <hr/>
            {% for user in users %}
            <a href='profiles/{{ user.username }}/'>{{ user.username }}</a><br/>
            {% empty %}
            <p>No users found</p>
            {% endfor %}
        </div>
    </div>
{% endblock content %}