src/accounts/api/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from tweets.api.views import (
    TweetListAPIView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/tweet/$', TweetListAPIView.as_view(), name='list'),
]

src/accounts/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from .views import (
    UserDetailView,
    UserFollowView,
    UserUpdateView,
    UserProfileUpdateView,
    )

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url="/")),
    # url(r'^$', TweetListAPIView.as_view(), name='list'), # /api/tweet/
    # url(r'^create/$', TweetCreateAPIView.as_view(), name='create'), # /api/tweet/
    # url(r'^create/$', TweetCreateView.as_view(), name='create'),
    url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<username>[\w.@+-]+)/follow/$', UserFollowView.as_view(), name='follow'),
    # 現状使用していない
    url(r'^(?P<username>[\w.@+-]+)/update/$', UserUpdateView.as_view(), name='update'),
    url(r'^(?P<username>[\w.@+-]+)/update_profile/$', UserProfileUpdateView.as_view(), name='update_profile'),
    # url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete')
]

src/ethvalu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import UserRegisterView
from hashtags.api.views import TagTweetAPIView
from hashtags.views import HashTagView
from tweets.views import TweetListView
from tweets.api.views import SearchTweetAPIView
from .views import home, SearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^$', TweetListView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^profiles/', include('accounts.urls', namespace='profiles')),
    url(r'^tokens/', include('tokens.urls', namespace='tokens')),
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagTweetAPIView.as_view(), name='tag-tweet-api'),
    url(r'^api/search/$', SearchTweetAPIView.as_view(), name='search-api'),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    url(r'^api/', include('accounts.api.urls', namespace='profiles-api')),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^transaction/', include('transactions.urls', namespace='transaction')),
]

if settings.DEBUG:
    urlpatterns+= (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns+= (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/tokens/urls.py
from django.conf.urls import url
from .views import (
	BuyUserTokenView,
    SellUserTokenView,
	BuyTokenView,
    SellTokenView,
	BuyTokenConfirmView,
    SellTokenConfirmView,
	MyAssetTokensView,
    TokenIssueView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/buy_token$', BuyUserTokenView.as_view(), name='buy_token'),
    url(r'^(?P<username>[\w.@+-]+)/sell_token$', SellUserTokenView.as_view(), name='sell_token'),
    url(r'^(?P<username>[\w.@+-]+)/buy/$', BuyTokenView.as_view(), name='buy'),
    url(r'^(?P<username>[\w.@+-]+)/sell/$', SellTokenView.as_view(), name='sell'),
    url(r'^(?P<username>[\w.@+-]+)/buy/confirm$', BuyTokenConfirmView.as_view(), name='buy_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/sell/confirm$', SellTokenConfirmView.as_view(), name='sell_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/asset$', MyAssetTokensView.as_view(), name='asset'),
    url(r'^issue/$', TokenIssueView.as_view(), name='issue'),
    # url(r'^buy/$', BuyTokenView.as_view(), name='buy')
]

src/transactions/urls.py
from django.conf.urls import url

from .views import (
    SendTransactionView,
    SendTokenTransactionView,
    )

urlpatterns = [
url(r'^send_transaction/$', SendTransactionView.as_view(), name='send'),
url(r'^send_token_transaction/$', SendTokenTransactionView.as_view(), name='sendtoken')
]

src/accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.urls import reverse_lazy
from django.template.defaultfilters import register
from web3 import Web3, HTTPProvider, KeepAliveRPCProvider
from tokens.models import Token

import json
# Create your models here.

class UserProfileManager(models.Manager):
    use_for_related_fields = True

    def all(self):
        qs = self.get_queryset().all()
        try:
            if self.instance:
                qs = qs.exclude(user=self.instance)
        except:
            pass
        return qs

    def toggle_follow(self, user, to_toggle_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if to_toggle_user in user_profile.following.all():
            user_profile.following.remove(to_toggle_user)
            added = False
        else:
            user_profile.following.add(to_toggle_user)
            added = True
        return added

    def is_following(self, user, followed_by_user):
        user_profile, created = UserProfile.objects.get_or_create(user=user)
        if created:
            return False
        if followed_by_user in user_profile.following.all():
            return True
        return False

    def recommended(self, user, limit_to=10):
        profile = user.profile
        following = profile.following.all()
        following = profile.get_following()
        qs = self.get_queryset().exclude(user__in=following).exclude(
            id=profile.id).order_by("?")[:limit_to]
        return qs


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name='profile')
    following = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='followed_by')
    image = models.ImageField(upload_to='profile_image', blank=True)
    token_address = models.CharField(blank=True, max_length=255)
    objects = UserProfileManager()
    have_token = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='have_token')

    def __str__(self):
        return str(self.user)

    def get_following(self):
        users = self.following.all()
        return users.exclude(username=self.user.username)

    def get_follow_url(self):
        return reverse_lazy(
            "profiles:follow",
            kwargs={"username": self.user.username})

    def get_absolute_url(self):
        return reverse_lazy(
            "profiles:detail",
            kwargs={"username": self.user.username})

    def get_have_token(self):
        users = self.have_token.all()
        return users.exclude(username=self.user.username)

    def get_buy_token_url(self):
        return reverse_lazy(
            "tokens:buy_token",
            kwargs={"username": self.user.username})

    def get_sell_token_url(self):
        return reverse_lazy(
            "tokens:sell_token",
            kwargs={"username": self.user.username})

class WalletProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        primary_key=True,
        related_name='wallet')
    num = models.CharField(
        blank=True,
        null=False,
        max_length=40,)
    balance = models.BigIntegerField(
        default=0,
        null=False,
    )
    # TODO: 売却中トークンのマスターを取得
    selling_token = models.BigIntegerField(
        default=0,
        null=False,
    )
    token_balance = models.BigIntegerField(
        default=0,
        null=False,
    )

    def get_token_lot(self, token_address):
        web3 = Web3(KeepAliveRPCProvider(host='localhost', port='8545'))
        web3.personal.unlockAccount(self.num, self.user.username)
        f = open("transactions/abi.json", 'r')
        abi = json.loads(f.read())
        # TODO: トークンごとにアドレスを取得
        cnt = web3.eth.contract(abi, token_address)
        tokenlot = cnt.call().balanceOf(self.num)
        # print(tokenlot)
        return tokenlot

    def __str__(self):
        return self.num
class WalletToken(models.Model):
    token = models.ForeignKey(WalletProfile)


def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    # print(instance)
    if created:
        new_profile = UserProfile.objects.get_or_create(user=instance)


post_save.connect(post_save_user_receiver, sender=settings.AUTH_USER_MODEL)

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserProfile

User = get_user_model()

class UserRegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Password must match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError("This username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("This email already exists")
        return email

# 現状使用しない方針
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name',
                  'last_name',
                  'email']

class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image',]

src/accounts/views.py
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from django.views.generic import DetailView
from django.views import View
from django.shortcuts import get_object_or_404, redirect
from django.views.generic.edit import FormView, UpdateView
from django.core.urlresolvers import reverse_lazy

from web3 import Web3, KeepAliveRPCProvider

from .forms import UserRegisterForm, UserUpdateForm, UserProfileUpdateForm
from .models import UserProfile,WalletProfile

# Create your views here.

User = get_user_model()


class UserRegisterView(FormView):
    template_name = 'accounts/user_register_form.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):
        web3 = Web3(KeepAliveRPCProvider(host='localhost', port='8545'))
        if web3.isConnected():
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            new_user = User.objects.create(username=username, email=email)
            new_user.set_password(password)
            # host='localhost' port=8545 は　geth のデフォルト値
            wallet_num = web3.personal.newAccount(username)
            # geth サーバーにアクセスしてwallet発行
            wallet = WalletProfile.objects.create(user=new_user)
            # Userモデルに格納するwalletオブジェクトを生成
            new_user.wallet.num = wallet_num
            wallet.save()
            # wallet.saveでuser.wallet.numにセーブ
            new_user.save()
            return super(UserRegisterView, self).form_valid(form)
        else:
            raise PermissionDenied
            return 0


class UserDetailView(DetailView):
    template_name = 'accounts/user_detail.html'
    queryset = User.objects.all()
    slug_field = 'username'

    def __calc_balance(usr):
        web3 = Web3(KeepAliveRPCProvider(host='localhost', port='8545'))
        user = User.objects.get(username=usr.kwargs.get("username"))
        print(user.wallet) #walletidを確認する用に便利なので、少し残しておく
        user.wallet.balance = web3.eth.getBalance(user.wallet.num)/100000
        user.wallet.save()
        return 0

    def get_object(self):
        user = User.objects.get(username=self.kwargs.get("username"))
        UserDetailView.__calc_balance(self)
        return get_object_or_404(
            User,
            username__iexact=self.kwargs.get("username")
        )

    def get_context_data(self, *args, **kwargs):
        context = super(UserDetailView, self).get_context_data(*args, **kwargs)
        following = UserProfile.objects.is_following(
            self.request.user,
            self.get_object())
        context['following'] = following
        context['recommended'] = UserProfile.objects.recommended(self.request.user)
        return context

class UserFollowView(View):
    def get(self, request: object, username: object, args: object, kwargs: object) -> object:
        toggle_user = get_object_or_404(User, username__iexact=username)
        if request.user.is_authenticated():
            is_following = UserProfile.objects.toggle_follow(request.user, toggle_user)
        return redirect("profiles:detail", username=username)


# 現状使用していない
class UserUpdateView(UpdateView):
    template_name = 'accounts/user_update.html'
    form_class = UserUpdateForm
    success_url = reverse_lazy('home')

    def get_object(self):
        obj = get_object_or_404(
                User,
                username__iexact=self.kwargs.get("username")
                )
        if not obj.username == self.request.user.username:
            raise PermissionDenied
        else:
            return obj


class UserProfileUpdateView(UpdateView):
    template_name = 'accounts/user_update.html'
    form_class = UserProfileUpdateForm
    success_url = reverse_lazy('home')

    def get_object(self):
        obj = get_object_or_404(
                UserProfile,
                user=self.request.user
                )
        if not obj.user == self.request.user:
            raise PermissionDenied
        else:
            return obj

src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}
{% block script %}
{% load get_token_value %}
<script>
    $(document).ready(function(){
        loadTweetContainer("tweet-container")
    });
</script>
{% endblock script %}

{% block content %}
<div class='row'>
    <div class='col-sm-3 col-xs-12'>
        <h1>{{ object.username }}</h1>
        {% if object.profile.image %}
        <img class="img-rounded" src="{{ object.profile.image.url }}" width="240">
        {% endif %}
        <p>Followers: {{ object.followed_by.all.count }}</p>
        <p>{{ user.wallet.balance }}:ETH
        <br>

        <p>所有トークン<br>
        {% for user in object.profile.have_token.all %}
            <a href="../{{ user.username }}">{{ user.username }}</a>:{{ user|get_token_value:object }}<br/>
        {% empty %}
            <p> トークンを持っていません
        {% endfor %}

        <form id='send-form' class="navbar-form navbar-left" method='POST' action='{% url "transaction:send" %}'>
            {% csrf_token %}

            <div class="form-group">
                <input class="form-control" type='hidden' name='username' value="{{ object }}"/>
                <input class="form-control" type='text' name='value' placeholder='value' value="{{ request.POST.value }}"/>
            </div>
            <input class="btn btn-default" type='submit' value='value' />
        </form>


            <a class='btn btn-link' href='{{ object.profile.get_follow_url }}'>{% if following %} UnFollow {% else %} Follow {% endif %}
            </a>
            <!-- 編集中 -->
            <a class='btn btn-link' href='{{ object.profile.get_buy_token_url }}'>BUY</a>
            <a class='btn btn-link' href='{{ object.profile.get_sell_token_url }}'>SELL</a>
            <p>{% if request.user.username == object.username %}
            <form type="submit" method="POST" name='issue' action='{% url "tokens:issue" %}'>
                {% csrf_token %}
                <input class="btn btn-default" value='発行' type="submit" />
            </form>
            {% endif %}

        </p>
        <hr/>
        <h1>Following <small>{{ object.profile.get_following.count }}</small></h1>
        {% for user in object.profile.get_following %}
            <a href='../{{ user.username }}'>{{ user.username }}</a><br/>
        {% empty %}
        <h4>Not following any  users</h4>
        {% endfor %}

        <hr/>
        <h1>Followed By</h1>
        {% for profile in object.followed_by.all %}
            <a href="../{{ profile.user.username }}">{{ profile.user.username }}</a><br/>
        {% empty %}
        <h4>Not followed by any users</h4>
        {% endfor %}

    </div>
    <div class='col-sm-9 col-xs-12'>
        <h1>Tweets</h1>

        <div id='tweet-container' data-url='/api/{{ object.username }}/tweet/'></div>
        <a href='#' id='loadmore'>Load More</a>


    </div>
</div>
{% endblock content %}

src/accounts/templates/accounts/user_register_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register | {{ block.super }}{% endblock title %}

{% block content %}
<div class='row'>
    <div class='col-sm-6 col-sm-offset-3'>
        <h1>Register</h1>
        <form class='form {% if form_class %}{{ form_class }}{% endif %}' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
        {% csrf_token %}
        {{ form|crispy }}
        <!-- <textarea class="form-control" rows="3"></textarea> -->
        <input class='btn btn-primary' type="submit" value="Register" />
        </form>
    </div>
</div>
{% endblock content %}

src/accounts/templates/accounts/user_update.html
{% extends "base.html" %}
{% block content %}
<div class='row'>
<div class='col-sm-4 col-sm-offset-4'>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if request.user.profile.image %}
        <img src="{{ request.user.profile.image.url }}" width=100%>
        <br />
        {% endif %}
        {{ form.as_p }}
        <br />
        <input class='btn btn-primary' type="submit" name="form" value="Submit" />
    </form>
</div>
</div>
{% endblock content %}