src/ethvalu/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import UserRegisterView
from hashtags.api.views import TagTweetAPIView
from hashtags.views import HashTagView
from tweets.views import TweetListView
from tweets.api.views import SearchTweetAPIView
from .views import home, SearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^$', TweetListView.as_view(), name='home'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^profiles/', include('accounts.urls', namespace='profiles')),
    url(r'^tokens/', include('tokens.urls', namespace='tokens')),
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagTweetAPIView.as_view(), name='tag-tweet-api'),
    url(r'^api/search/$', SearchTweetAPIView.as_view(), name='search-api'),
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    url(r'^api/', include('accounts.api.urls', namespace='profiles-api')),
    url(r'^register/$', UserRegisterView.as_view(), name='register'),
    url(r'^transaction/', include('transactions.urls', namespace='transaction')),
]

if settings.DEBUG:
    urlpatterns+= (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns+= (static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

src/tokens/urls.py
from django.conf.urls import url
from .views import (
	BuyUserTokenView,
    SellUserTokenView,
	BuyTokenView,
    SellTokenView,
	BuyTokenConfirmView,
    SellTokenConfirmView,
	MyAssetTokensView,
    TokenIssueView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/buy_token$', BuyUserTokenView.as_view(), name='buy_token'),
    url(r'^(?P<username>[\w.@+-]+)/sell_token$', SellUserTokenView.as_view(), name='sell_token'),
    url(r'^(?P<username>[\w.@+-]+)/buy/$', BuyTokenView.as_view(), name='buy'),
    url(r'^(?P<username>[\w.@+-]+)/sell/$', SellTokenView.as_view(), name='sell'),
    url(r'^(?P<username>[\w.@+-]+)/buy/confirm$', BuyTokenConfirmView.as_view(), name='buy_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/sell/confirm$', SellTokenConfirmView.as_view(), name='sell_confirm'),
    url(r'^(?P<username>[\w.@+-]+)/asset$', MyAssetTokensView.as_view(), name='asset'),
    url(r'^issue/$', TokenIssueView.as_view(), name='issue'),
    # url(r'^buy/$', BuyTokenView.as_view(), name='buy')
]

src/tokens/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.views.generic import (
    DetailView)
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import ObjectDoesNotExist

from web3 import Web3, HTTPProvider, KeepAliveRPCProvider

from .models import Token, BuyOrder, SellOrder, TokenBoard
from accounts.models import WalletProfile, UserProfile

import sys, json
from time import sleep

User = get_user_model()


# Create your views here.

class BuyUserTokenView(DetailView):
    template_name = 'tokens/buy_user_tokens.html'

    def get_context_data(self, **kwargs):
        context = super(BuyUserTokenView, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.kwargs.get("username"))
        context['sells'] = SellOrder.objects.get_summed_lot(user)
        context['buys'] = BuyOrder.objects.get_summed_lot(user)
        context['buy_lists'] = BuyOrder.objects.get_summed_list(user)
        context['sell_lists'] = SellOrder.objects.get_summed_list(user)
        return context

    def get_object(self):
        # user = User.objects.get(username=self.kwargs.get("username"))
        return get_object_or_404(
            User,
            username__iexact=self.kwargs.get("username")
        )


class SellUserTokenView(DetailView):
    template_name = 'tokens/sell_user_tokens.html'

    def get_context_data(self, **kwargs):
        context = super(SellUserTokenView, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.kwargs.get("username"))
        context['sells'] = SellOrder.objects.get_summed_lot(user)
        context['buys'] = BuyOrder.objects.get_summed_lot(user)
        context['buy_lists'] = BuyOrder.objects.get_summed_list(user)
        context['sell_lists'] = SellOrder.objects.get_summed_list(user)
        TokenBoard.object.get_seller(user)
        return context

    def get_object(self):
        # user = User.objects.get(username=self.kwargs.get("username"))
        return get_object_or_404(
            User,
            username__iexact=self.kwargs.get("username")
        )


# TODO: BuyTokenView, BuyTokenConfirmView をformsで書き換え
class BuyTokenView(LoginRequiredMixin, View):
    """Token購入するView。売買板の表示と、BuyTokenConfirmViewへの遷移をする
    """

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated():
            master = User.objects.get(username=self.kwargs.get("username"))
            lot = request.POST.get("lot")
            price = request.POST.get("value")
            # TODO: formでバリデーションとる&変数型変換
            if int(lot) <= 0 or float(price) <= 0:
                return HttpResponse("Invalid input")
            context = {
                'master': master,
                'buyer': request.user,
                'price': price,
                'lot': lot,
            }
            return render(request, "tokens/buy_confirm.html", context=context)


# TODO: SellTokenView, SellTokenConfirmView をformsで書き換え
class SellTokenView(LoginRequiredMixin, View):
    """Token購入するView。売買板の表示と、SellTokenConfirmViewへの遷移をする
    """

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated():
            master = User.objects.get(username=self.kwargs.get("username"))
            lot = request.POST.get("lot")
            price = request.POST.get("value")
            # TODO: formでバリデーションとる&変数型変換
            if int(lot) <= 0 or float(price) <= 0:
                return HttpResponse("Invalid input")
            context = {
                'master': master,
                'seller': request.user,
                'price': price,
                'lot': lot,
            }
            return render(request, "tokens/sell_confirm.html", context=context)


class BuyTokenConfirmView(LoginRequiredMixin, View):
    """Token購入の確認をするView
    """

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated():
            master = User.objects.get(username=self.kwargs.get("username"))
            lot = request.POST.get("lot")
            price = request.POST.get("value")
            # TODO: formでバリデーションとる&変数型変換
            if int(lot) <= 0 or float(price) <= 0:
                return HttpResponse("Invalid input")
            buyer = User.objects.get(username=request.user.username)
            password = request.POST.get("password")
            success = buyer.check_password(password)
            # TODO: formでvalidation取るようにする
            if success:
                obj = BuyOrder(
                    master=master,
                    buyer=request.user,
                    price=price,
                    lot=lot,
                )
                obj.save()
                try:

                    exist = SellOrder.objects.filter(
                        price__icontains=price, master=master).first()
                except SellOrder.DoesNotExist:
                    exist = None
                # if SellOrder.objects.get(price__iexact=price) is not None:

                if exist is not None:
                    seller = SellOrder.objects.filter(master=master, price=price)[0].seller
                    if int(lot) <= SellOrder.objects.filter(master=master, price=price)[0].lot:
                        seller.wallet.selling_token -= int(lot)
                        seller.wallet.save()
                    else:
                        seller.wallet.selling_token = SellOrder.objects.filter(master=master, price=price)[0].lot
                    send_token_transaction(buyer,
                                           int(obj.lot),
                                           master.profile.token_address,
                                           False,
                                           seller,)
                    token_transaction_check(SellOrder.objects.filter(master=master, price=price)[0],
                                            BuyOrder.objects.filter(master=master, buyer=buyer, price=price)[0])

                    print(seller.wallet.selling_token)

                    buyer.save()
                return redirect("home")

            else:
                return HttpResponse("Password Incorrect")


class SellTokenConfirmView(LoginRequiredMixin, View):
    """Token購入の確認をするView
    """

    def post(self, request, *args, **kwargs):
        if request.method == 'POST' and request.user.is_authenticated():
            master = User.objects.get(username=self.kwargs.get("username"))
            lot = request.POST.get("lot")
            price = request.POST.get("value")
            # TODO: formでバリデーションとる&変数型変換
            if int(lot) <= 0 or float(price) <= 0:
                return HttpResponse("Invalid input")

            seller = User.objects.get(username=request.user.username)
            seller_wallet = seller.wallet
            # TODO 各自のユーザーのアドレスへ
            print(seller.profile.token_address)
            token_address = master.profile.token_address
            print(token_address)
            seller_lot = seller.wallet.get_token_lot(token_address)
            selling_token = seller.wallet.selling_token
            if (seller_lot - selling_token) < int(lot):
                return HttpResponse("token足りない")
            password = request.POST.get("password")
            success = seller.check_password(password)
            # TODO: formでvalidation取るようにする
            if success:
                obj = SellOrder(
                    master=master,
                    seller=request.user,
                    price=price,
                    lot=lot,
                )

                obj.save()
                try:

                    exist = BuyOrder.objects.filter(
                        price__icontains=price, master=master).first()

                except BuyOrder.DoesNotExist:
                    exist = None
                if exist is not None:
                    buyer = BuyOrder.objects.filter(master=master, price=price)[0].buyer
                    token_transaction_check(BuyOrder.objects.filter(master=master,
                                                                    price=price)[0],
                                            SellOrder.objects.filter(master=master,
                                                                     seller=seller,
                                                                     price=price)[0])
                    send_token_transaction(buyer,
                                           int(obj.lot),
                                           token_address,
                                           False,
                                           seller)
                else:
                    seller.wallet.selling_token += int(obj.lot)
                    seller.wallet.save()

                print(seller.wallet.selling_token)
                return redirect("home")
            else:
                return HttpResponse("Password Incorrect")


class MyAssetTokensView(LoginRequiredMixin, DetailView):
    """保持しているTokenの情報を表示するページ
    """
    template_name = 'tokens/asset_token.html'

    def get_object(self):
        # user = User.objects.get(username=self.kwargs.get("username"))
        return get_object_or_404(
            User,
            username__iexact=self.kwargs.get("username")
        )

    def get_context_data(self, *args, **kwargs):
        context = super(MyAssetTokensView, self).get_context_data(
            *args, **kwargs)
        requested_user = User.objects.get(username=self.kwargs.get("username"))
        requesting_user = self.request.user
        if not requested_user == requesting_user:
            raise PermissionDenied
        token = Token.objects.filter(buyer=requested_user)

src/tokens/templates/tokens/_trade_chart.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
<script type="text/javascript">
    var ctx = document.getElementById("tradeChart");

    backgroundColor = []
    borderColor = []
    var sellList = {{sell_lists|safe}}
    var sellPrice = sellList[0]
    var sellLot = sellList[1]
    for (i = 0; i < sellPrice.length; i++) {
        backgroundColor.push('rgba(255, 99, 132, 0.2)')
        borderColor.push('rgba(255, 99, 132, 1)')
    }

    var buyList = {{buy_lists|safe}}
    var buyPrice = buyList[0]
    var buyLot = buyList[1]
    for (i = 0; i < buyPrice.length; i++) {
        backgroundColor.push('rgba(54, 162, 235, 0.2)')
        borderColor.push('rgba(54, 162, 235, 1)')
    }

    price = sellPrice.concat(buyPrice)
    lot = sellLot.concat(buyLot)
    

    var tradeChart = new Chart(ctx, {
        type: 'horizontalBar',
        data: {
            labels: price,
            datasets: [{
                // label: '# of Votes',
                data: lot,
                backgroundColor: backgroundColor,
                borderColor: borderColor,
                borderWidth: 1,
            }]
        },
        options: {
            scales: {
                xAxes: [{
                    ticks: {
                        beginAtZero:true,
                        stepSize: 1
                    },
                }],
                yAxes: [{
                    barThickness: 20,
                }],
            },
            legend: {
                display: false,
            },

        }
    });
</script>

src/tokens/templates/tokens/asset_token.html
{% extends "base.html" %}
{% block content %}
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
    <p>My Tokens</p>
    {% for token in tokens %}
    <hr/>
	<p>publisher:{{token.publisher}}</p>
	<p>bought_price:{{token.bought_price}}</p>
	<p>latest_price:{{token.latest_price}}</p>
	<p>lot:{{token.lot}}</p>
	<p>updated:{{token.updated}}</p>
	<p>timestamp:{{token.timestamp}}</p>
	{% endfor %}
    </div>
</div>
{% endblock content %}

src/tokens/templates/tokens/buy_confirm.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <p>{{master}}のトークンを以下の条件で購入します</p>
        <form method="POST" action='{% url "tokens:buy_confirm" username=master %}'>
            {% csrf_token %}
            <div class="form-group">
                <b>購入希望数</b>
                <input class="form-control" type='hidden' name='username' value="{{ object }}"/>
                <input class="form-control" id="input_amount" name="lot" type="number" value="{{lot}}" placeholder='{{lot}}' required />
                <p>BLO</p>
            </div>  
            <div class="form-group" style="margin-top: 10px">
                <b>購入希望単価</b>
                <input class="form-control" id="buy_price" name="value" type="float" value="{{price}}" placeholder='{{price}}' required />
                <p>ETH</p>
            </div>
            <div class="form-group">
                <b>Password</b>
                <input class="form-control" id="input_amount" name="password" type='password' placeholder='認証のためパスワードを入力してください' required />
            </div>  
            <div class="ref_price">
                <b>参考価格</b>
                <!-- <em><span id="ref_price">{% if price %}{{price}}{% else %}-{% endif %}</span><small>JPY</small></em> -->
                <em><span id="ref_price">---</span><small>JPY</small></em>
            </div>
            <div class="go_confirmpage">
                <input class="btn btn-primary btn_go_confirm" type="submit" value="購入">
            </div>
         </form>
    </div>
</div>
{% endblock content %}

src/tokens/templates/tokens/buy_user_tokens.html
{% extends "base.html" %}

{% block script %}
<!-- <script>
    $(document).ready(function(){
        loadTweetContainer("tweet-container")
    });
</script> -->
{% include "tokens/_trade_chart.html" %}
{% endblock script %}

{% block content %}
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <h1>{{ object.username }}</h1>
        {% if object.profile.image %}
        <img class="img-rounded" src="{{ object.profile.image.url }}" width="240">
        {% endif %}
        <p>Followers: {{ object.followed_by.all.count }}</p>
        <p>{{ user.wallet.balance }}:BLOW
            <a class='btn btn-link' href='{{ object.profile.get_follow_url }}'>{% if following %} UnFollow {% else %} Follow {% endif %}
            </a>
        </p>
        <hr/>

        <!-- ソースコード参考 -->
        <div id="hint_chart">
        <table>
        <thead>
        <tr><td class="r0">買気配値</td><td class="r1">買BLO数</td><td class="r2">価格</td><td class="r3">売BLO数</td><td class="r4">売気配値</td></tr>
        </thead>
        <tbody>
            <!-- template loopで回す -->

            <!-- <tr class="sale"><td class="r0"></td><td class="r1"></td><th class="r2"><a href="購入欄に数値設定するURL">{{ price }}</a></th><td class="r3">{{ salenumber }}</td><td class="r4"><p class="bar" style="width: {{ width }}%;"></p></td></tr> -->
            {% for sell in sells %}
            <tr class="sell"><td class="r0"><p class="bar" style="width: 100%;"></p></td><td class="r1"></td><th class="r2"><a href="#">{{ sell.price }}</a></th><td class="r3">{{ sell.lot }}</td><td class="r4"></td></tr>
            {% endfor %}

            <!-- ここもtemplate loopで回す -->
            {% for buy in buys %}
            <tr class="buy"><td class="r0"><p class="bar" style="width: 100%;"></p></td><td class="r1">{{ buy.lot }}</td><th class="r2"><a href="#">{{ buy.price }}</a></th><td class="r3"></td><td class="r4"></td></tr>
            {% endfor %}
        </tbody>
        </table>
        </div>
        <hr/>
        <canvas id="tradeChart" width="400"></canvas>
        <!-- hogehogeはtokenidかな -->
        <form method="POST" action='{% url "tokens:buy" username=object.username %}'>
            {% csrf_token %}
            <div class="form-group">
                <b>購入希望数</b>
                <input class="form-control" type='hidden' name='username' value="{{ object }}"/>
                <input class="form-control" id="input_amount" name="lot" type="number" value="{{ request.POST.lot }}" placeholder='購入希望数'>
                <p>BLO</p>
            </div>  
            <div class="form-group" style="margin-top: 10px">
                <b>購入希望単価</b>
                <!-- 以下valueも変数で与える -->
                <input class="form-control" id="input_rate" name="value" type="float" value="{{ request.POST.value }}" placeholder='購入希望単価'>
                <p>ETH</p>
            </div>
                            <div class="ref_price">
                <b>参考価格</b>
                <!-- <em><span id="ref_price">{% if price %}{{price}}{% else %}-{% endif %}</span><small>JPY</small></em> -->
                <em><span id="ref_price">---</span><small>JPY</small></em>
            </div>
                <div class="go_confirmpage">
                <input class="btn btn-primary btn_go_confirm" type="submit" value="購入確認画面へ" name='buy'>
                </div>
            <div class="buy_sell_count">
                <span>本日の残り取引回数</span>
                <b>10</b>
                <small>回</small>
            </div>
         </form>
         <!-- ソースコード参考〜ここまで〜 -->
    </div>
</div>
{% endblock content %}

src/tokens/templates/tokens/sell_confirm.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <p>{{master}}のトークンを以下の条件で売却します</p>
        <form method="POST" action='{% url "tokens:sell_confirm" username=master %}'>
            {% csrf_token %}
            <div class="form-group">
                <b>売却希望数</b>
                <input class="form-control" type='hidden' name='username' value="{{ object }}"/>
                <input class="form-control" id="input_amount" name="lot" type="number" value="{{lot}}" placeholder='{{lot}}' required />
                <p>BLO</p>
            </div>  
            <div class="form-group" style="margin-top: 10px">
                <b>売却希望単価</b>
                <input class="form-control" id="sell_price" name="value" type="float" value="{{price}}" placeholder='{{price}}' required />
                <p>ETH</p>
            </div>
            <div class="form-group">
                <b>Password</b>
                <input class="form-control" id="input_amount" name="password" type='password' placeholder='認証のためパスワードを入力してください' required />
            </div>  
            <div class="ref_price">
                <b>参考価格</b>
                <!-- <em><span id="ref_price">{% if price %}{{price}}{% else %}-{% endif %}</span><small>JPY</small></em> -->
                <em><span id="ref_price">---</span><small>JPY</small></em>
            </div>
            <div class="go_confirmpage">
                <input class="btn btn-primary btn_go_confirm" type="submit" value="購入">
            </div>
         </form>
    </div>
</div>
{% endblock content %}

src/tokens/templates/tokens/sell_user_tokens.html
{% extends "base.html" %}

{% block script %}
<!-- <script>
    $(document).ready(function(){
        loadTweetContainer("tweet-container")
    });
</script> -->
{% include "tokens/_trade_chart.html" %}
{% endblock script %}

{% block content %}
<div class='row'>
    <div class='col-md-8 col-md-offset-2'>
        <h1>{{ object.username }}</h1>
        {% if object.profile.image %}
        <img class="img-rounded" src="{{ object.profile.image.url }}" width="240">
        {% endif %}
        <p>Followers: {{ object.followed_by.all.count }}</p>
        <p>{{ user.wallet.balance }}:BLOW
            <a class='btn btn-link' href='{{ object.profile.get_follow_url }}'>{% if following %} UnFollow {% else %} Follow {% endif %}
            </a>
        </p>
        <hr/>

        <!-- ソースコード参考 -->
        <div id="hint_chart">
        <table>
        <thead>
        <tr><td class="r0">買気配値</td><td class="r1">買BLO数</td><td class="r2">価格</td><td class="r3">売BLO数</td><td class="r4">売気配値</td></tr>
        </thead>
        <tbody>
            <!-- template loopで回す -->

            <!-- <tr class="sale"><td class="r0"></td><td class="r1"></td><th class="r2"><a href="購入欄に数値設定するURL">{{ price }}</a></th><td class="r3">{{ salenumber }}</td><td class="r4"><p class="bar" style="width: {{ width }}%;"></p></td></tr> -->
            {% for sell in sells %}
            <tr class="sell"><td class="r0"><p class="bar" style="width: 100%;"></p></td><td class="r1"></td><th class="r2"><a href="#">{{ sell.price }}</a></th><td class="r3">{{ sell.lot }}</td><td class="r4"></td></tr>
            {% endfor %}

            <!-- ここもtemplate loopで回す -->
            {% for buy in buys %}
            <tr class="buy"><td class="r0"><p class="bar" style="width: 100%;"></p></td><td class="r1">{{ buy.lot }}</td><th class="r2"><a href="#">{{ buy.price }}</a></th><td class="r3"></td><td class="r4"></td></tr>
            {% endfor %}
        </tbody>
        </table>
        </div>
        <hr/>
        <canvas id="tradeChart" width="400"></canvas>
        <!-- hogehogeはtokenidかな -->
        <form method="POST" action='{% url "tokens:sell" username=object.username %}'>
            {% csrf_token %}
            <div class="form-group">
                <b>売却希望数</b>
                <input class="form-control" type='hidden' name='username' value="{{ object }}"/>
                <input class="form-control" id="input_amount" name="lot" type="number" value="{{ request.POST.lot }}" placeholder='売却希望数'>
                <p>BLO</p>
            </div>  
            <div class="form-group" style="margin-top: 10px">
                <b>売却希望単価</b>
                <!-- 以下valueも変数で与える -->
                <input class="form-control" id="input_rate" name="value" type="float" value="{{ request.POST.value }}" placeholder='売却希望単価'>
                <p>ETH</p>
            </div>
                            <div class="ref_price">
                <b>参考価格</b>
                <!-- <em><span id="ref_price">{% if price %}{{price}}{% else %}-{% endif %}</span><small>JPY</small></em> -->
                <em><span id="ref_price">---</span><small>JPY</small></em>
            </div>
                <div class="go_confirmpage">
                <input class="btn btn-primary btn_go_confirm" type="submit" value="売却確認画面へ" name='sell'>
                </div>
            <div class="buy_sell_count">
                <span>本日の残り取引回数</span>
                <b>10</b>
                <small>回</small>
            </div>
         </form>
         <!-- ソースコード参考〜ここまで〜 -->
    </div>
</div>
{% endblock content %}